// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=team_list
//

// Package team_list is a generated GoMock package.
package team_list

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockteamLister is a mock of teamLister interface.
type MockteamLister struct {
	ctrl     *gomock.Controller
	recorder *MockteamListerMockRecorder
	isgomock struct{}
}

// MockteamListerMockRecorder is the mock recorder for MockteamLister.
type MockteamListerMockRecorder struct {
	mock *MockteamLister
}

// NewMockteamLister creates a new mock instance.
func NewMockteamLister(ctrl *gomock.Controller) *MockteamLister {
	mock := &MockteamLister{ctrl: ctrl}
	mock.recorder = &MockteamListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamLister) EXPECT() *MockteamListerMockRecorder {
	return m.recorder
}

// ListByUser mocks base method.
func (m *MockteamLister) ListByUser(ctx context.Context, userID int64) ([]models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockteamListerMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockteamLister)(nil).ListByUser), ctx, userID)
}
