// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=task_history
//

// Package task_history is a generated GoMock package.
package task_history

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MocktaskHistoryReader is a mock of taskHistoryReader interface.
type MocktaskHistoryReader struct {
	ctrl     *gomock.Controller
	recorder *MocktaskHistoryReaderMockRecorder
	isgomock struct{}
}

// MocktaskHistoryReaderMockRecorder is the mock recorder for MocktaskHistoryReader.
type MocktaskHistoryReaderMockRecorder struct {
	mock *MocktaskHistoryReader
}

// NewMocktaskHistoryReader creates a new mock instance.
func NewMocktaskHistoryReader(ctrl *gomock.Controller) *MocktaskHistoryReader {
	mock := &MocktaskHistoryReader{ctrl: ctrl}
	mock.recorder = &MocktaskHistoryReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskHistoryReader) EXPECT() *MocktaskHistoryReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocktaskHistoryReader) GetByID(ctx context.Context, id int64) (*models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktaskHistoryReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktaskHistoryReader)(nil).GetByID), ctx, id)
}

// History mocks base method.
func (m *MocktaskHistoryReader) History(ctx context.Context, taskID int64) ([]models.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", ctx, taskID)
	ret0, _ := ret[0].([]models.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MocktaskHistoryReaderMockRecorder) History(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MocktaskHistoryReader)(nil).History), ctx, taskID)
}

// MockteamMembershipReader is a mock of teamMembershipReader interface.
type MockteamMembershipReader struct {
	ctrl     *gomock.Controller
	recorder *MockteamMembershipReaderMockRecorder
	isgomock struct{}
}

// MockteamMembershipReaderMockRecorder is the mock recorder for MockteamMembershipReader.
type MockteamMembershipReaderMockRecorder struct {
	mock *MockteamMembershipReader
}

// NewMockteamMembershipReader creates a new mock instance.
func NewMockteamMembershipReader(ctrl *gomock.Controller) *MockteamMembershipReader {
	mock := &MockteamMembershipReader{ctrl: ctrl}
	mock.recorder = &MockteamMembershipReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamMembershipReader) EXPECT() *MockteamMembershipReaderMockRecorder {
	return m.recorder
}

// GetMemberRole mocks base method.
func (m *MockteamMembershipReader) GetMemberRole(ctx context.Context, teamID, userID int64) (models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRole", ctx, teamID, userID)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRole indicates an expected call of GetMemberRole.
func (mr *MockteamMembershipReaderMockRecorder) GetMemberRole(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRole", reflect.TypeOf((*MockteamMembershipReader)(nil).GetMemberRole), ctx, teamID, userID)
}
