// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=report_team_summary
//

// Package report_team_summary is a generated GoMock package.
package report_team_summary

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockteamSummaryReader is a mock of teamSummaryReader interface.
type MockteamSummaryReader struct {
	ctrl     *gomock.Controller
	recorder *MockteamSummaryReaderMockRecorder
	isgomock struct{}
}

// MockteamSummaryReaderMockRecorder is the mock recorder for MockteamSummaryReader.
type MockteamSummaryReaderMockRecorder struct {
	mock *MockteamSummaryReader
}

// NewMockteamSummaryReader creates a new mock instance.
func NewMockteamSummaryReader(ctrl *gomock.Controller) *MockteamSummaryReader {
	mock := &MockteamSummaryReader{ctrl: ctrl}
	mock.recorder = &MockteamSummaryReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamSummaryReader) EXPECT() *MockteamSummaryReaderMockRecorder {
	return m.recorder
}

// TeamSummary mocks base method.
func (m *MockteamSummaryReader) TeamSummary(ctx context.Context, managerID int64) ([]models.TeamSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TeamSummary", ctx, managerID)
	ret0, _ := ret[0].([]models.TeamSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TeamSummary indicates an expected call of TeamSummary.
func (mr *MockteamSummaryReaderMockRecorder) TeamSummary(ctx, managerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TeamSummary", reflect.TypeOf((*MockteamSummaryReader)(nil).TeamSummary), ctx, managerID)
}

// MockreportAccessChecker is a mock of reportAccessChecker interface.
type MockreportAccessChecker struct {
	ctrl     *gomock.Controller
	recorder *MockreportAccessCheckerMockRecorder
	isgomock struct{}
}

// MockreportAccessCheckerMockRecorder is the mock recorder for MockreportAccessChecker.
type MockreportAccessCheckerMockRecorder struct {
	mock *MockreportAccessChecker
}

// NewMockreportAccessChecker creates a new mock instance.
func NewMockreportAccessChecker(ctrl *gomock.Controller) *MockreportAccessChecker {
	mock := &MockreportAccessChecker{ctrl: ctrl}
	mock.recorder = &MockreportAccessCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreportAccessChecker) EXPECT() *MockreportAccessCheckerMockRecorder {
	return m.recorder
}

// HasManagementRole mocks base method.
func (m *MockreportAccessChecker) HasManagementRole(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasManagementRole", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasManagementRole indicates an expected call of HasManagementRole.
func (mr *MockreportAccessCheckerMockRecorder) HasManagementRole(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasManagementRole", reflect.TypeOf((*MockreportAccessChecker)(nil).HasManagementRole), ctx, userID)
}
