// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=report_top_creators
//

// Package report_top_creators is a generated GoMock package.
package report_top_creators

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MocktopCreatorsReader is a mock of topCreatorsReader interface.
type MocktopCreatorsReader struct {
	ctrl     *gomock.Controller
	recorder *MocktopCreatorsReaderMockRecorder
	isgomock struct{}
}

// MocktopCreatorsReaderMockRecorder is the mock recorder for MocktopCreatorsReader.
type MocktopCreatorsReaderMockRecorder struct {
	mock *MocktopCreatorsReader
}

// NewMocktopCreatorsReader creates a new mock instance.
func NewMocktopCreatorsReader(ctrl *gomock.Controller) *MocktopCreatorsReader {
	mock := &MocktopCreatorsReader{ctrl: ctrl}
	mock.recorder = &MocktopCreatorsReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktopCreatorsReader) EXPECT() *MocktopCreatorsReaderMockRecorder {
	return m.recorder
}

// TopCreatorsByTeam mocks base method.
func (m *MocktopCreatorsReader) TopCreatorsByTeam(ctx context.Context, managerID int64) ([]models.TopCreator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopCreatorsByTeam", ctx, managerID)
	ret0, _ := ret[0].([]models.TopCreator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopCreatorsByTeam indicates an expected call of TopCreatorsByTeam.
func (mr *MocktopCreatorsReaderMockRecorder) TopCreatorsByTeam(ctx, managerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopCreatorsByTeam", reflect.TypeOf((*MocktopCreatorsReader)(nil).TopCreatorsByTeam), ctx, managerID)
}

// MockreportAccessChecker is a mock of reportAccessChecker interface.
type MockreportAccessChecker struct {
	ctrl     *gomock.Controller
	recorder *MockreportAccessCheckerMockRecorder
	isgomock struct{}
}

// MockreportAccessCheckerMockRecorder is the mock recorder for MockreportAccessChecker.
type MockreportAccessCheckerMockRecorder struct {
	mock *MockreportAccessChecker
}

// NewMockreportAccessChecker creates a new mock instance.
func NewMockreportAccessChecker(ctrl *gomock.Controller) *MockreportAccessChecker {
	mock := &MockreportAccessChecker{ctrl: ctrl}
	mock.recorder = &MockreportAccessCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreportAccessChecker) EXPECT() *MockreportAccessCheckerMockRecorder {
	return m.recorder
}

// HasManagementRole mocks base method.
func (m *MockreportAccessChecker) HasManagementRole(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasManagementRole", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasManagementRole indicates an expected call of HasManagementRole.
func (mr *MockreportAccessCheckerMockRecorder) HasManagementRole(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasManagementRole", reflect.TypeOf((*MockreportAccessChecker)(nil).HasManagementRole), ctx, userID)
}
