// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=task_history
//

// Package task_history is a generated GoMock package.
package task_history

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MocktaskHistoryReader is a mock of taskHistoryReader interface.
type MocktaskHistoryReader struct {
	ctrl     *gomock.Controller
	recorder *MocktaskHistoryReaderMockRecorder
	isgomock struct{}
}

// MocktaskHistoryReaderMockRecorder is the mock recorder for MocktaskHistoryReader.
type MocktaskHistoryReaderMockRecorder struct {
	mock *MocktaskHistoryReader
}

// NewMocktaskHistoryReader creates a new mock instance.
func NewMocktaskHistoryReader(ctrl *gomock.Controller) *MocktaskHistoryReader {
	mock := &MocktaskHistoryReader{ctrl: ctrl}
	mock.recorder = &MocktaskHistoryReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskHistoryReader) EXPECT() *MocktaskHistoryReaderMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MocktaskHistoryReader) GetHistory(ctx context.Context, actorID, taskID int64) ([]models.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, actorID, taskID)
	ret0, _ := ret[0].([]models.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MocktaskHistoryReaderMockRecorder) GetHistory(ctx, actorID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MocktaskHistoryReader)(nil).GetHistory), ctx, actorID, taskID)
}
