// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=task_list
//

// Package task_list is a generated GoMock package.
package task_list

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MocktaskLister is a mock of taskLister interface.
type MocktaskLister struct {
	ctrl     *gomock.Controller
	recorder *MocktaskListerMockRecorder
	isgomock struct{}
}

// MocktaskListerMockRecorder is the mock recorder for MocktaskLister.
type MocktaskListerMockRecorder struct {
	mock *MocktaskLister
}

// NewMocktaskLister creates a new mock instance.
func NewMocktaskLister(ctrl *gomock.Controller) *MocktaskLister {
	mock := &MocktaskLister{ctrl: ctrl}
	mock.recorder = &MocktaskListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskLister) EXPECT() *MocktaskListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MocktaskLister) List(ctx context.Context, filter models.TaskFilter, requesterID int64) (models.TaskList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, requesterID)
	ret0, _ := ret[0].(models.TaskList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocktaskListerMockRecorder) List(ctx, filter, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocktaskLister)(nil).List), ctx, filter, requesterID)
}

// MockteamMembershipReader is a mock of teamMembershipReader interface.
type MockteamMembershipReader struct {
	ctrl     *gomock.Controller
	recorder *MockteamMembershipReaderMockRecorder
	isgomock struct{}
}

// MockteamMembershipReaderMockRecorder is the mock recorder for MockteamMembershipReader.
type MockteamMembershipReaderMockRecorder struct {
	mock *MockteamMembershipReader
}

// NewMockteamMembershipReader creates a new mock instance.
func NewMockteamMembershipReader(ctrl *gomock.Controller) *MockteamMembershipReader {
	mock := &MockteamMembershipReader{ctrl: ctrl}
	mock.recorder = &MockteamMembershipReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamMembershipReader) EXPECT() *MockteamMembershipReaderMockRecorder {
	return m.recorder
}

// GetMemberRole mocks base method.
func (m *MockteamMembershipReader) GetMemberRole(ctx context.Context, teamID, userID int64) (models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRole", ctx, teamID, userID)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRole indicates an expected call of GetMemberRole.
func (mr *MockteamMembershipReaderMockRecorder) GetMemberRole(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRole", reflect.TypeOf((*MockteamMembershipReader)(nil).GetMemberRole), ctx, teamID, userID)
}

// MocktaskListCache is a mock of taskListCache interface.
type MocktaskListCache struct {
	ctrl     *gomock.Controller
	recorder *MocktaskListCacheMockRecorder
	isgomock struct{}
}

// MocktaskListCacheMockRecorder is the mock recorder for MocktaskListCache.
type MocktaskListCacheMockRecorder struct {
	mock *MocktaskListCache
}

// NewMocktaskListCache creates a new mock instance.
func NewMocktaskListCache(ctrl *gomock.Controller) *MocktaskListCache {
	mock := &MocktaskListCache{ctrl: ctrl}
	mock.recorder = &MocktaskListCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskListCache) EXPECT() *MocktaskListCacheMockRecorder {
	return m.recorder
}

// GetTaskList mocks base method.
func (m *MocktaskListCache) GetTaskList(ctx context.Context, key string) (models.TaskList, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskList", ctx, key)
	ret0, _ := ret[0].(models.TaskList)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTaskList indicates an expected call of GetTaskList.
func (mr *MocktaskListCacheMockRecorder) GetTaskList(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskList", reflect.TypeOf((*MocktaskListCache)(nil).GetTaskList), ctx, key)
}

// SetTaskList mocks base method.
func (m *MocktaskListCache) SetTaskList(ctx context.Context, key string, value models.TaskList, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTaskList", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTaskList indicates an expected call of SetTaskList.
func (mr *MocktaskListCacheMockRecorder) SetTaskList(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTaskList", reflect.TypeOf((*MocktaskListCache)(nil).SetTaskList), ctx, key, value, ttl)
}
