// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=team_create
//

// Package team_create is a generated GoMock package.
package team_create

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"
	team_create "task-service/internal/usecase/team_create"

	gomock "go.uber.org/mock/gomock"
)

// MockteamCreator is a mock of teamCreator interface.
type MockteamCreator struct {
	ctrl     *gomock.Controller
	recorder *MockteamCreatorMockRecorder
	isgomock struct{}
}

// MockteamCreatorMockRecorder is the mock recorder for MockteamCreator.
type MockteamCreatorMockRecorder struct {
	mock *MockteamCreator
}

// NewMockteamCreator creates a new mock instance.
func NewMockteamCreator(ctrl *gomock.Controller) *MockteamCreator {
	mock := &MockteamCreator{ctrl: ctrl}
	mock.recorder = &MockteamCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamCreator) EXPECT() *MockteamCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockteamCreator) Create(ctx context.Context, ownerID int64, input team_create.Input) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ownerID, input)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockteamCreatorMockRecorder) Create(ctx, ownerID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockteamCreator)(nil).Create), ctx, ownerID, input)
}
