// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=report_invalid_assignees
//

// Package report_invalid_assignees is a generated GoMock package.
package report_invalid_assignees

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockinvalidAssigneesReader is a mock of invalidAssigneesReader interface.
type MockinvalidAssigneesReader struct {
	ctrl     *gomock.Controller
	recorder *MockinvalidAssigneesReaderMockRecorder
	isgomock struct{}
}

// MockinvalidAssigneesReaderMockRecorder is the mock recorder for MockinvalidAssigneesReader.
type MockinvalidAssigneesReaderMockRecorder struct {
	mock *MockinvalidAssigneesReader
}

// NewMockinvalidAssigneesReader creates a new mock instance.
func NewMockinvalidAssigneesReader(ctrl *gomock.Controller) *MockinvalidAssigneesReader {
	mock := &MockinvalidAssigneesReader{ctrl: ctrl}
	mock.recorder = &MockinvalidAssigneesReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinvalidAssigneesReader) EXPECT() *MockinvalidAssigneesReaderMockRecorder {
	return m.recorder
}

// InvalidAssignees mocks base method.
func (m *MockinvalidAssigneesReader) InvalidAssignees(ctx context.Context, managerID int64) ([]models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidAssignees", ctx, managerID)
	ret0, _ := ret[0].([]models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvalidAssignees indicates an expected call of InvalidAssignees.
func (mr *MockinvalidAssigneesReaderMockRecorder) InvalidAssignees(ctx, managerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidAssignees", reflect.TypeOf((*MockinvalidAssigneesReader)(nil).InvalidAssignees), ctx, managerID)
}

// MockreportAccessChecker is a mock of reportAccessChecker interface.
type MockreportAccessChecker struct {
	ctrl     *gomock.Controller
	recorder *MockreportAccessCheckerMockRecorder
	isgomock struct{}
}

// MockreportAccessCheckerMockRecorder is the mock recorder for MockreportAccessChecker.
type MockreportAccessCheckerMockRecorder struct {
	mock *MockreportAccessChecker
}

// NewMockreportAccessChecker creates a new mock instance.
func NewMockreportAccessChecker(ctrl *gomock.Controller) *MockreportAccessChecker {
	mock := &MockreportAccessChecker{ctrl: ctrl}
	mock.recorder = &MockreportAccessCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreportAccessChecker) EXPECT() *MockreportAccessCheckerMockRecorder {
	return m.recorder
}

// HasManagementRole mocks base method.
func (m *MockreportAccessChecker) HasManagementRole(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasManagementRole", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasManagementRole indicates an expected call of HasManagementRole.
func (mr *MockreportAccessCheckerMockRecorder) HasManagementRole(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasManagementRole", reflect.TypeOf((*MockreportAccessChecker)(nil).HasManagementRole), ctx, userID)
}
