// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=report_invalid_assignees
//

// Package report_invalid_assignees is a generated GoMock package.
package report_invalid_assignees

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockinvalidAssigneesProvider is a mock of invalidAssigneesProvider interface.
type MockinvalidAssigneesProvider struct {
	ctrl     *gomock.Controller
	recorder *MockinvalidAssigneesProviderMockRecorder
	isgomock struct{}
}

// MockinvalidAssigneesProviderMockRecorder is the mock recorder for MockinvalidAssigneesProvider.
type MockinvalidAssigneesProviderMockRecorder struct {
	mock *MockinvalidAssigneesProvider
}

// NewMockinvalidAssigneesProvider creates a new mock instance.
func NewMockinvalidAssigneesProvider(ctrl *gomock.Controller) *MockinvalidAssigneesProvider {
	mock := &MockinvalidAssigneesProvider{ctrl: ctrl}
	mock.recorder = &MockinvalidAssigneesProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinvalidAssigneesProvider) EXPECT() *MockinvalidAssigneesProviderMockRecorder {
	return m.recorder
}

// GetInvalidAssignees mocks base method.
func (m *MockinvalidAssigneesProvider) GetInvalidAssignees(ctx context.Context, managerID int64) ([]models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvalidAssignees", ctx, managerID)
	ret0, _ := ret[0].([]models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvalidAssignees indicates an expected call of GetInvalidAssignees.
func (mr *MockinvalidAssigneesProviderMockRecorder) GetInvalidAssignees(ctx, managerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvalidAssignees", reflect.TypeOf((*MockinvalidAssigneesProvider)(nil).GetInvalidAssignees), ctx, managerID)
}
