// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=team_create
//

// Package team_create is a generated GoMock package.
package team_create

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockteamCreator is a mock of teamCreator interface.
type MockteamCreator struct {
	ctrl     *gomock.Controller
	recorder *MockteamCreatorMockRecorder
	isgomock struct{}
}

// MockteamCreatorMockRecorder is the mock recorder for MockteamCreator.
type MockteamCreatorMockRecorder struct {
	mock *MockteamCreator
}

// NewMockteamCreator creates a new mock instance.
func NewMockteamCreator(ctrl *gomock.Controller) *MockteamCreator {
	mock := &MockteamCreator{ctrl: ctrl}
	mock.recorder = &MockteamCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamCreator) EXPECT() *MockteamCreatorMockRecorder {
	return m.recorder
}

// CreateWithOwner mocks base method.
func (m *MockteamCreator) CreateWithOwner(ctx context.Context, team *models.Team, ownerID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithOwner", ctx, team, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithOwner indicates an expected call of CreateWithOwner.
func (mr *MockteamCreatorMockRecorder) CreateWithOwner(ctx, team, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithOwner", reflect.TypeOf((*MockteamCreator)(nil).CreateWithOwner), ctx, team, ownerID)
}
