// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=auth_register
//

// Package auth_register is a generated GoMock package.
package auth_register

import (
	context "context"
	reflect "reflect"
	auth_register "task-service/internal/usecase/auth_register"

	gomock "go.uber.org/mock/gomock"
)

// MockuserRegistrar is a mock of userRegistrar interface.
type MockuserRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockuserRegistrarMockRecorder
	isgomock struct{}
}

// MockuserRegistrarMockRecorder is the mock recorder for MockuserRegistrar.
type MockuserRegistrarMockRecorder struct {
	mock *MockuserRegistrar
}

// NewMockuserRegistrar creates a new mock instance.
func NewMockuserRegistrar(ctrl *gomock.Controller) *MockuserRegistrar {
	mock := &MockuserRegistrar{ctrl: ctrl}
	mock.recorder = &MockuserRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRegistrar) EXPECT() *MockuserRegistrarMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockuserRegistrar) Register(ctx context.Context, input auth_register.Input) (*auth_register.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, input)
	ret0, _ := ret[0].(*auth_register.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockuserRegistrarMockRecorder) Register(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockuserRegistrar)(nil).Register), ctx, input)
}
