// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=outbox_dispatch
//

// Package outbox_dispatch is a generated GoMock package.
package outbox_dispatch

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockeventStore is a mock of eventStore interface.
type MockeventStore struct {
	ctrl     *gomock.Controller
	recorder *MockeventStoreMockRecorder
	isgomock struct{}
}

// MockeventStoreMockRecorder is the mock recorder for MockeventStore.
type MockeventStoreMockRecorder struct {
	mock *MockeventStore
}

// NewMockeventStore creates a new mock instance.
func NewMockeventStore(ctrl *gomock.Controller) *MockeventStore {
	mock := &MockeventStore{ctrl: ctrl}
	mock.recorder = &MockeventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventStore) EXPECT() *MockeventStoreMockRecorder {
	return m.recorder
}

// ClaimPending mocks base method.
func (m *MockeventStore) ClaimPending(ctx context.Context, limit int) ([]models.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPending", ctx, limit)
	ret0, _ := ret[0].([]models.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPending indicates an expected call of ClaimPending.
func (mr *MockeventStoreMockRecorder) ClaimPending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPending", reflect.TypeOf((*MockeventStore)(nil).ClaimPending), ctx, limit)
}

// MarkDeadLetter mocks base method.
func (m *MockeventStore) MarkDeadLetter(ctx context.Context, id int64, claimToken, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDeadLetter", ctx, id, claimToken, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDeadLetter indicates an expected call of MarkDeadLetter.
func (mr *MockeventStoreMockRecorder) MarkDeadLetter(ctx, id, claimToken, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDeadLetter", reflect.TypeOf((*MockeventStore)(nil).MarkDeadLetter), ctx, id, claimToken, message)
}

// MarkFailed mocks base method.
func (m *MockeventStore) MarkFailed(ctx context.Context, id int64, claimToken string, retryAt time.Time, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, claimToken, retryAt, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockeventStoreMockRecorder) MarkFailed(ctx, id, claimToken, retryAt, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockeventStore)(nil).MarkFailed), ctx, id, claimToken, retryAt, message)
}

// MarkProcessed mocks base method.
func (m *MockeventStore) MarkProcessed(ctx context.Context, id int64, claimToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, id, claimToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockeventStoreMockRecorder) MarkProcessed(ctx, id, claimToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockeventStore)(nil).MarkProcessed), ctx, id, claimToken)
}

// MockinviteSender is a mock of inviteSender interface.
type MockinviteSender struct {
	ctrl     *gomock.Controller
	recorder *MockinviteSenderMockRecorder
	isgomock struct{}
}

// MockinviteSenderMockRecorder is the mock recorder for MockinviteSender.
type MockinviteSenderMockRecorder struct {
	mock *MockinviteSender
}

// NewMockinviteSender creates a new mock instance.
func NewMockinviteSender(ctrl *gomock.Controller) *MockinviteSender {
	mock := &MockinviteSender{ctrl: ctrl}
	mock.recorder = &MockinviteSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinviteSender) EXPECT() *MockinviteSenderMockRecorder {
	return m.recorder
}

// SendInvite mocks base method.
func (m *MockinviteSender) SendInvite(ctx context.Context, toEmail, teamName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInvite", ctx, toEmail, teamName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInvite indicates an expected call of SendInvite.
func (mr *MockinviteSenderMockRecorder) SendInvite(ctx, toEmail, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInvite", reflect.TypeOf((*MockinviteSender)(nil).SendInvite), ctx, toEmail, teamName)
}
