// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=auth_login
//

// Package auth_login is a generated GoMock package.
package auth_login

import (
	context "context"
	reflect "reflect"
	auth_login "task-service/internal/usecase/auth_login"

	gomock "go.uber.org/mock/gomock"
)

// Mockauthenticator is a mock of authenticator interface.
type Mockauthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockauthenticatorMockRecorder
	isgomock struct{}
}

// MockauthenticatorMockRecorder is the mock recorder for Mockauthenticator.
type MockauthenticatorMockRecorder struct {
	mock *Mockauthenticator
}

// NewMockauthenticator creates a new mock instance.
func NewMockauthenticator(ctrl *gomock.Controller) *Mockauthenticator {
	mock := &Mockauthenticator{ctrl: ctrl}
	mock.recorder = &MockauthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockauthenticator) EXPECT() *MockauthenticatorMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *Mockauthenticator) Login(ctx context.Context, input auth_login.Input) (*auth_login.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, input)
	ret0, _ := ret[0].(*auth_login.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockauthenticatorMockRecorder) Login(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*Mockauthenticator)(nil).Login), ctx, input)
}
