// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=task_list
//

// Package task_list is a generated GoMock package.
package task_list

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MocktaskLister is a mock of taskLister interface.
type MocktaskLister struct {
	ctrl     *gomock.Controller
	recorder *MocktaskListerMockRecorder
	isgomock struct{}
}

// MocktaskListerMockRecorder is the mock recorder for MocktaskLister.
type MocktaskListerMockRecorder struct {
	mock *MocktaskLister
}

// NewMocktaskLister creates a new mock instance.
func NewMocktaskLister(ctrl *gomock.Controller) *MocktaskLister {
	mock := &MocktaskLister{ctrl: ctrl}
	mock.recorder = &MocktaskListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskLister) EXPECT() *MocktaskListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MocktaskLister) List(ctx context.Context, actorID int64, filter models.TaskFilter) (models.TaskList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, actorID, filter)
	ret0, _ := ret[0].(models.TaskList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocktaskListerMockRecorder) List(ctx, actorID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocktaskLister)(nil).List), ctx, actorID, filter)
}
