// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=team_delete
//

// Package team_delete is a generated GoMock package.
package team_delete

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockteamOwnerReader is a mock of teamOwnerReader interface.
type MockteamOwnerReader struct {
	ctrl     *gomock.Controller
	recorder *MockteamOwnerReaderMockRecorder
	isgomock struct{}
}

// MockteamOwnerReaderMockRecorder is the mock recorder for MockteamOwnerReader.
type MockteamOwnerReaderMockRecorder struct {
	mock *MockteamOwnerReader
}

// NewMockteamOwnerReader creates a new mock instance.
func NewMockteamOwnerReader(ctrl *gomock.Controller) *MockteamOwnerReader {
	mock := &MockteamOwnerReader{ctrl: ctrl}
	mock.recorder = &MockteamOwnerReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamOwnerReader) EXPECT() *MockteamOwnerReaderMockRecorder {
	return m.recorder
}

// GetMemberRole mocks base method.
func (m *MockteamOwnerReader) GetMemberRole(ctx context.Context, teamID, userID int64) (models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRole", ctx, teamID, userID)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRole indicates an expected call of GetMemberRole.
func (mr *MockteamOwnerReaderMockRecorder) GetMemberRole(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRole", reflect.TypeOf((*MockteamOwnerReader)(nil).GetMemberRole), ctx, teamID, userID)
}

// MockteamDeleter is a mock of teamDeleter interface.
type MockteamDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockteamDeleterMockRecorder
	isgomock struct{}
}

// MockteamDeleterMockRecorder is the mock recorder for MockteamDeleter.
type MockteamDeleterMockRecorder struct {
	mock *MockteamDeleter
}

// NewMockteamDeleter creates a new mock instance.
func NewMockteamDeleter(ctrl *gomock.Controller) *MockteamDeleter {
	mock := &MockteamDeleter{ctrl: ctrl}
	mock.recorder = &MockteamDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamDeleter) EXPECT() *MockteamDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockteamDeleter) Delete(ctx context.Context, teamID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockteamDeleterMockRecorder) Delete(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockteamDeleter)(nil).Delete), ctx, teamID)
}

// MocktaskCacheInvalidator is a mock of taskCacheInvalidator interface.
type MocktaskCacheInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MocktaskCacheInvalidatorMockRecorder
	isgomock struct{}
}

// MocktaskCacheInvalidatorMockRecorder is the mock recorder for MocktaskCacheInvalidator.
type MocktaskCacheInvalidatorMockRecorder struct {
	mock *MocktaskCacheInvalidator
}

// NewMocktaskCacheInvalidator creates a new mock instance.
func NewMocktaskCacheInvalidator(ctrl *gomock.Controller) *MocktaskCacheInvalidator {
	mock := &MocktaskCacheInvalidator{ctrl: ctrl}
	mock.recorder = &MocktaskCacheInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskCacheInvalidator) EXPECT() *MocktaskCacheInvalidatorMockRecorder {
	return m.recorder
}

// DeleteTeamTasks mocks base method.
func (m *MocktaskCacheInvalidator) DeleteTeamTasks(ctx context.Context, teamID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeamTasks", ctx, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeamTasks indicates an expected call of DeleteTeamTasks.
func (mr *MocktaskCacheInvalidatorMockRecorder) DeleteTeamTasks(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeamTasks", reflect.TypeOf((*MocktaskCacheInvalidator)(nil).DeleteTeamTasks), ctx, teamID)
}
