// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=task_create
//

// Package task_create is a generated GoMock package.
package task_create

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MocktaskCreator is a mock of taskCreator interface.
type MocktaskCreator struct {
	ctrl     *gomock.Controller
	recorder *MocktaskCreatorMockRecorder
	isgomock struct{}
}

// MocktaskCreatorMockRecorder is the mock recorder for MocktaskCreator.
type MocktaskCreatorMockRecorder struct {
	mock *MocktaskCreator
}

// NewMocktaskCreator creates a new mock instance.
func NewMocktaskCreator(ctrl *gomock.Controller) *MocktaskCreator {
	mock := &MocktaskCreator{ctrl: ctrl}
	mock.recorder = &MocktaskCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskCreator) EXPECT() *MocktaskCreatorMockRecorder {
	return m.recorder
}

// CreateWithHistory mocks base method.
func (m *MocktaskCreator) CreateWithHistory(ctx context.Context, task *models.Task, history *models.TaskHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithHistory", ctx, task, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithHistory indicates an expected call of CreateWithHistory.
func (mr *MocktaskCreatorMockRecorder) CreateWithHistory(ctx, task, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithHistory", reflect.TypeOf((*MocktaskCreator)(nil).CreateWithHistory), ctx, task, history)
}

// MockteamMembershipReader is a mock of teamMembershipReader interface.
type MockteamMembershipReader struct {
	ctrl     *gomock.Controller
	recorder *MockteamMembershipReaderMockRecorder
	isgomock struct{}
}

// MockteamMembershipReaderMockRecorder is the mock recorder for MockteamMembershipReader.
type MockteamMembershipReaderMockRecorder struct {
	mock *MockteamMembershipReader
}

// NewMockteamMembershipReader creates a new mock instance.
func NewMockteamMembershipReader(ctrl *gomock.Controller) *MockteamMembershipReader {
	mock := &MockteamMembershipReader{ctrl: ctrl}
	mock.recorder = &MockteamMembershipReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamMembershipReader) EXPECT() *MockteamMembershipReaderMockRecorder {
	return m.recorder
}

// GetMemberRole mocks base method.
func (m *MockteamMembershipReader) GetMemberRole(ctx context.Context, teamID, userID int64) (models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRole", ctx, teamID, userID)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRole indicates an expected call of GetMemberRole.
func (mr *MockteamMembershipReaderMockRecorder) GetMemberRole(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRole", reflect.TypeOf((*MockteamMembershipReader)(nil).GetMemberRole), ctx, teamID, userID)
}

// MocktaskCacheInvalidator is a mock of taskCacheInvalidator interface.
type MocktaskCacheInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MocktaskCacheInvalidatorMockRecorder
	isgomock struct{}
}

// MocktaskCacheInvalidatorMockRecorder is the mock recorder for MocktaskCacheInvalidator.
type MocktaskCacheInvalidatorMockRecorder struct {
	mock *MocktaskCacheInvalidator
}

// NewMocktaskCacheInvalidator creates a new mock instance.
func NewMocktaskCacheInvalidator(ctrl *gomock.Controller) *MocktaskCacheInvalidator {
	mock := &MocktaskCacheInvalidator{ctrl: ctrl}
	mock.recorder = &MocktaskCacheInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskCacheInvalidator) EXPECT() *MocktaskCacheInvalidatorMockRecorder {
	return m.recorder
}

// DeleteTeamTasks mocks base method.
func (m *MocktaskCacheInvalidator) DeleteTeamTasks(ctx context.Context, teamID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeamTasks", ctx, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeamTasks indicates an expected call of DeleteTeamTasks.
func (mr *MocktaskCacheInvalidatorMockRecorder) DeleteTeamTasks(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeamTasks", reflect.TypeOf((*MocktaskCacheInvalidator)(nil).DeleteTeamTasks), ctx, teamID)
}
