// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=task_create
//

// Package task_create is a generated GoMock package.
package task_create

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"
	task_create "task-service/internal/usecase/task_create"

	gomock "go.uber.org/mock/gomock"
)

// MocktaskCreator is a mock of taskCreator interface.
type MocktaskCreator struct {
	ctrl     *gomock.Controller
	recorder *MocktaskCreatorMockRecorder
	isgomock struct{}
}

// MocktaskCreatorMockRecorder is the mock recorder for MocktaskCreator.
type MocktaskCreatorMockRecorder struct {
	mock *MocktaskCreator
}

// NewMocktaskCreator creates a new mock instance.
func NewMocktaskCreator(ctrl *gomock.Controller) *MocktaskCreator {
	mock := &MocktaskCreator{ctrl: ctrl}
	mock.recorder = &MocktaskCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskCreator) EXPECT() *MocktaskCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocktaskCreator) Create(ctx context.Context, actorID int64, input task_create.Input) (*models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, actorID, input)
	ret0, _ := ret[0].(*models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocktaskCreatorMockRecorder) Create(ctx, actorID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocktaskCreator)(nil).Create), ctx, actorID, input)
}
