// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=task_update
//

// Package task_update is a generated GoMock package.
package task_update

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"
	task_update "task-service/internal/usecase/task_update"

	gomock "go.uber.org/mock/gomock"
)

// MocktaskUpdater is a mock of taskUpdater interface.
type MocktaskUpdater struct {
	ctrl     *gomock.Controller
	recorder *MocktaskUpdaterMockRecorder
	isgomock struct{}
}

// MocktaskUpdaterMockRecorder is the mock recorder for MocktaskUpdater.
type MocktaskUpdaterMockRecorder struct {
	mock *MocktaskUpdater
}

// NewMocktaskUpdater creates a new mock instance.
func NewMocktaskUpdater(ctrl *gomock.Controller) *MocktaskUpdater {
	mock := &MocktaskUpdater{ctrl: ctrl}
	mock.recorder = &MocktaskUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskUpdater) EXPECT() *MocktaskUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MocktaskUpdater) Update(ctx context.Context, actorID, taskID int64, input task_update.Input) (*models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, actorID, taskID, input)
	ret0, _ := ret[0].(*models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MocktaskUpdaterMockRecorder) Update(ctx, actorID, taskID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MocktaskUpdater)(nil).Update), ctx, actorID, taskID, input)
}
