// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=auth_login
//

// Package auth_login is a generated GoMock package.
package auth_login

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockuserFinder is a mock of userFinder interface.
type MockuserFinder struct {
	ctrl     *gomock.Controller
	recorder *MockuserFinderMockRecorder
	isgomock struct{}
}

// MockuserFinderMockRecorder is the mock recorder for MockuserFinder.
type MockuserFinderMockRecorder struct {
	mock *MockuserFinder
}

// NewMockuserFinder creates a new mock instance.
func NewMockuserFinder(ctrl *gomock.Controller) *MockuserFinder {
	mock := &MockuserFinder{ctrl: ctrl}
	mock.recorder = &MockuserFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserFinder) EXPECT() *MockuserFinderMockRecorder {
	return m.recorder
}

// FindByEmail mocks base method.
func (m *MockuserFinder) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockuserFinderMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockuserFinder)(nil).FindByEmail), ctx, email)
}

// MockpasswordComparer is a mock of passwordComparer interface.
type MockpasswordComparer struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordComparerMockRecorder
	isgomock struct{}
}

// MockpasswordComparerMockRecorder is the mock recorder for MockpasswordComparer.
type MockpasswordComparerMockRecorder struct {
	mock *MockpasswordComparer
}

// NewMockpasswordComparer creates a new mock instance.
func NewMockpasswordComparer(ctrl *gomock.Controller) *MockpasswordComparer {
	mock := &MockpasswordComparer{ctrl: ctrl}
	mock.recorder = &MockpasswordComparerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordComparer) EXPECT() *MockpasswordComparerMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockpasswordComparer) Compare(hash, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", hash, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compare indicates an expected call of Compare.
func (mr *MockpasswordComparerMockRecorder) Compare(hash, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockpasswordComparer)(nil).Compare), hash, password)
}

// MocktokenIssuer is a mock of tokenIssuer interface.
type MocktokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MocktokenIssuerMockRecorder
	isgomock struct{}
}

// MocktokenIssuerMockRecorder is the mock recorder for MocktokenIssuer.
type MocktokenIssuerMockRecorder struct {
	mock *MocktokenIssuer
}

// NewMocktokenIssuer creates a new mock instance.
func NewMocktokenIssuer(ctrl *gomock.Controller) *MocktokenIssuer {
	mock := &MocktokenIssuer{ctrl: ctrl}
	mock.recorder = &MocktokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenIssuer) EXPECT() *MocktokenIssuerMockRecorder {
	return m.recorder
}

// NewToken mocks base method.
func (m *MocktokenIssuer) NewToken(user *models.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewToken", user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewToken indicates an expected call of NewToken.
func (mr *MocktokenIssuerMockRecorder) NewToken(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewToken", reflect.TypeOf((*MocktokenIssuer)(nil).NewToken), user)
}
