// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=task_update
//

// Package task_update is a generated GoMock package.
package task_update

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MocktaskUpdater is a mock of taskUpdater interface.
type MocktaskUpdater struct {
	ctrl     *gomock.Controller
	recorder *MocktaskUpdaterMockRecorder
	isgomock struct{}
}

// MocktaskUpdaterMockRecorder is the mock recorder for MocktaskUpdater.
type MocktaskUpdaterMockRecorder struct {
	mock *MocktaskUpdater
}

// NewMocktaskUpdater creates a new mock instance.
func NewMocktaskUpdater(ctrl *gomock.Controller) *MocktaskUpdater {
	mock := &MocktaskUpdater{ctrl: ctrl}
	mock.recorder = &MocktaskUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskUpdater) EXPECT() *MocktaskUpdaterMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocktaskUpdater) GetByID(ctx context.Context, id int64) (*models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktaskUpdaterMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktaskUpdater)(nil).GetByID), ctx, id)
}

// UpdateWithHistory mocks base method.
func (m *MocktaskUpdater) UpdateWithHistory(ctx context.Context, task *models.Task, history []models.TaskHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithHistory", ctx, task, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithHistory indicates an expected call of UpdateWithHistory.
func (mr *MocktaskUpdaterMockRecorder) UpdateWithHistory(ctx, task, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithHistory", reflect.TypeOf((*MocktaskUpdater)(nil).UpdateWithHistory), ctx, task, history)
}

// MockteamMembershipReader is a mock of teamMembershipReader interface.
type MockteamMembershipReader struct {
	ctrl     *gomock.Controller
	recorder *MockteamMembershipReaderMockRecorder
	isgomock struct{}
}

// MockteamMembershipReaderMockRecorder is the mock recorder for MockteamMembershipReader.
type MockteamMembershipReaderMockRecorder struct {
	mock *MockteamMembershipReader
}

// NewMockteamMembershipReader creates a new mock instance.
func NewMockteamMembershipReader(ctrl *gomock.Controller) *MockteamMembershipReader {
	mock := &MockteamMembershipReader{ctrl: ctrl}
	mock.recorder = &MockteamMembershipReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamMembershipReader) EXPECT() *MockteamMembershipReaderMockRecorder {
	return m.recorder
}

// GetMemberRole mocks base method.
func (m *MockteamMembershipReader) GetMemberRole(ctx context.Context, teamID, userID int64) (models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRole", ctx, teamID, userID)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRole indicates an expected call of GetMemberRole.
func (mr *MockteamMembershipReaderMockRecorder) GetMemberRole(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRole", reflect.TypeOf((*MockteamMembershipReader)(nil).GetMemberRole), ctx, teamID, userID)
}

// MocktaskCacheInvalidator is a mock of taskCacheInvalidator interface.
type MocktaskCacheInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MocktaskCacheInvalidatorMockRecorder
	isgomock struct{}
}

// MocktaskCacheInvalidatorMockRecorder is the mock recorder for MocktaskCacheInvalidator.
type MocktaskCacheInvalidatorMockRecorder struct {
	mock *MocktaskCacheInvalidator
}

// NewMocktaskCacheInvalidator creates a new mock instance.
func NewMocktaskCacheInvalidator(ctrl *gomock.Controller) *MocktaskCacheInvalidator {
	mock := &MocktaskCacheInvalidator{ctrl: ctrl}
	mock.recorder = &MocktaskCacheInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskCacheInvalidator) EXPECT() *MocktaskCacheInvalidatorMockRecorder {
	return m.recorder
}

// DeleteTeamTasks mocks base method.
func (m *MocktaskCacheInvalidator) DeleteTeamTasks(ctx context.Context, teamID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeamTasks", ctx, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeamTasks indicates an expected call of DeleteTeamTasks.
func (mr *MocktaskCacheInvalidatorMockRecorder) DeleteTeamTasks(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeamTasks", reflect.TypeOf((*MocktaskCacheInvalidator)(nil).DeleteTeamTasks), ctx, teamID)
}
