// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=outbox_cleanup
//

// Package outbox_cleanup is a generated GoMock package.
package outbox_cleanup

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockeventCleaner is a mock of eventCleaner interface.
type MockeventCleaner struct {
	ctrl     *gomock.Controller
	recorder *MockeventCleanerMockRecorder
	isgomock struct{}
}

// MockeventCleanerMockRecorder is the mock recorder for MockeventCleaner.
type MockeventCleanerMockRecorder struct {
	mock *MockeventCleaner
}

// NewMockeventCleaner creates a new mock instance.
func NewMockeventCleaner(ctrl *gomock.Controller) *MockeventCleaner {
	mock := &MockeventCleaner{ctrl: ctrl}
	mock.recorder = &MockeventCleanerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventCleaner) EXPECT() *MockeventCleanerMockRecorder {
	return m.recorder
}

// DeleteProcessedBefore mocks base method.
func (m *MockeventCleaner) DeleteProcessedBefore(ctx context.Context, before time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProcessedBefore", ctx, before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProcessedBefore indicates an expected call of DeleteProcessedBefore.
func (mr *MockeventCleanerMockRecorder) DeleteProcessedBefore(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProcessedBefore", reflect.TypeOf((*MockeventCleaner)(nil).DeleteProcessedBefore), ctx, before)
}
