// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=team_invite
//

// Package team_invite is a generated GoMock package.
package team_invite

import (
	context "context"
	reflect "reflect"
	team_invite "task-service/internal/usecase/team_invite"

	gomock "go.uber.org/mock/gomock"
)

// MockteamInviter is a mock of teamInviter interface.
type MockteamInviter struct {
	ctrl     *gomock.Controller
	recorder *MockteamInviterMockRecorder
	isgomock struct{}
}

// MockteamInviterMockRecorder is the mock recorder for MockteamInviter.
type MockteamInviterMockRecorder struct {
	mock *MockteamInviter
}

// NewMockteamInviter creates a new mock instance.
func NewMockteamInviter(ctrl *gomock.Controller) *MockteamInviter {
	mock := &MockteamInviter{ctrl: ctrl}
	mock.recorder = &MockteamInviterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamInviter) EXPECT() *MockteamInviterMockRecorder {
	return m.recorder
}

// Invite mocks base method.
func (m *MockteamInviter) Invite(ctx context.Context, inviterID, teamID int64, input team_invite.Input) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invite", ctx, inviterID, teamID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invite indicates an expected call of Invite.
func (mr *MockteamInviterMockRecorder) Invite(ctx, inviterID, teamID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invite", reflect.TypeOf((*MockteamInviter)(nil).Invite), ctx, inviterID, teamID, input)
}
