// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=team_delete
//

// Package team_delete is a generated GoMock package.
package team_delete

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockteamDeleter is a mock of teamDeleter interface.
type MockteamDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockteamDeleterMockRecorder
	isgomock struct{}
}

// MockteamDeleterMockRecorder is the mock recorder for MockteamDeleter.
type MockteamDeleterMockRecorder struct {
	mock *MockteamDeleter
}

// NewMockteamDeleter creates a new mock instance.
func NewMockteamDeleter(ctrl *gomock.Controller) *MockteamDeleter {
	mock := &MockteamDeleter{ctrl: ctrl}
	mock.recorder = &MockteamDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamDeleter) EXPECT() *MockteamDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockteamDeleter) Delete(ctx context.Context, ownerID, teamID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ownerID, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockteamDeleterMockRecorder) Delete(ctx, ownerID, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockteamDeleter)(nil).Delete), ctx, ownerID, teamID)
}
