// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=report_team_summary
//

// Package report_team_summary is a generated GoMock package.
package report_team_summary

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockteamSummaryProvider is a mock of teamSummaryProvider interface.
type MockteamSummaryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockteamSummaryProviderMockRecorder
	isgomock struct{}
}

// MockteamSummaryProviderMockRecorder is the mock recorder for MockteamSummaryProvider.
type MockteamSummaryProviderMockRecorder struct {
	mock *MockteamSummaryProvider
}

// NewMockteamSummaryProvider creates a new mock instance.
func NewMockteamSummaryProvider(ctrl *gomock.Controller) *MockteamSummaryProvider {
	mock := &MockteamSummaryProvider{ctrl: ctrl}
	mock.recorder = &MockteamSummaryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamSummaryProvider) EXPECT() *MockteamSummaryProviderMockRecorder {
	return m.recorder
}

// GetTeamSummary mocks base method.
func (m *MockteamSummaryProvider) GetTeamSummary(ctx context.Context, managerID int64) ([]models.TeamSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamSummary", ctx, managerID)
	ret0, _ := ret[0].([]models.TeamSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamSummary indicates an expected call of GetTeamSummary.
func (mr *MockteamSummaryProviderMockRecorder) GetTeamSummary(ctx, managerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamSummary", reflect.TypeOf((*MockteamSummaryProvider)(nil).GetTeamSummary), ctx, managerID)
}
