// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=team_invite
//

// Package team_invite is a generated GoMock package.
package team_invite

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockteamReader is a mock of teamReader interface.
type MockteamReader struct {
	ctrl     *gomock.Controller
	recorder *MockteamReaderMockRecorder
	isgomock struct{}
}

// MockteamReaderMockRecorder is the mock recorder for MockteamReader.
type MockteamReaderMockRecorder struct {
	mock *MockteamReader
}

// NewMockteamReader creates a new mock instance.
func NewMockteamReader(ctrl *gomock.Controller) *MockteamReader {
	mock := &MockteamReader{ctrl: ctrl}
	mock.recorder = &MockteamReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamReader) EXPECT() *MockteamReaderMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockteamReader) FindByID(ctx context.Context, id int64) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockteamReaderMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockteamReader)(nil).FindByID), ctx, id)
}

// GetMemberRole mocks base method.
func (m *MockteamReader) GetMemberRole(ctx context.Context, teamID, userID int64) (models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRole", ctx, teamID, userID)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRole indicates an expected call of GetMemberRole.
func (mr *MockteamReaderMockRecorder) GetMemberRole(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRole", reflect.TypeOf((*MockteamReader)(nil).GetMemberRole), ctx, teamID, userID)
}

// MockteamInviteStore is a mock of teamInviteStore interface.
type MockteamInviteStore struct {
	ctrl     *gomock.Controller
	recorder *MockteamInviteStoreMockRecorder
	isgomock struct{}
}

// MockteamInviteStoreMockRecorder is the mock recorder for MockteamInviteStore.
type MockteamInviteStoreMockRecorder struct {
	mock *MockteamInviteStore
}

// NewMockteamInviteStore creates a new mock instance.
func NewMockteamInviteStore(ctrl *gomock.Controller) *MockteamInviteStore {
	mock := &MockteamInviteStore{ctrl: ctrl}
	mock.recorder = &MockteamInviteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamInviteStore) EXPECT() *MockteamInviteStoreMockRecorder {
	return m.recorder
}

// AddMemberWithOutboxEvent mocks base method.
func (m *MockteamInviteStore) AddMemberWithOutboxEvent(ctx context.Context, teamID, userID int64, role models.Role, event *models.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMemberWithOutboxEvent", ctx, teamID, userID, role, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMemberWithOutboxEvent indicates an expected call of AddMemberWithOutboxEvent.
func (mr *MockteamInviteStoreMockRecorder) AddMemberWithOutboxEvent(ctx, teamID, userID, role, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMemberWithOutboxEvent", reflect.TypeOf((*MockteamInviteStore)(nil).AddMemberWithOutboxEvent), ctx, teamID, userID, role, event)
}

// FindByID mocks base method.
func (m *MockteamInviteStore) FindByID(ctx context.Context, id int64) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockteamInviteStoreMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockteamInviteStore)(nil).FindByID), ctx, id)
}

// GetMemberRole mocks base method.
func (m *MockteamInviteStore) GetMemberRole(ctx context.Context, teamID, userID int64) (models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRole", ctx, teamID, userID)
	ret0, _ := ret[0].(models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRole indicates an expected call of GetMemberRole.
func (mr *MockteamInviteStoreMockRecorder) GetMemberRole(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRole", reflect.TypeOf((*MockteamInviteStore)(nil).GetMemberRole), ctx, teamID, userID)
}

// MockteamMemberInviter is a mock of teamMemberInviter interface.
type MockteamMemberInviter struct {
	ctrl     *gomock.Controller
	recorder *MockteamMemberInviterMockRecorder
	isgomock struct{}
}

// MockteamMemberInviterMockRecorder is the mock recorder for MockteamMemberInviter.
type MockteamMemberInviterMockRecorder struct {
	mock *MockteamMemberInviter
}

// NewMockteamMemberInviter creates a new mock instance.
func NewMockteamMemberInviter(ctrl *gomock.Controller) *MockteamMemberInviter {
	mock := &MockteamMemberInviter{ctrl: ctrl}
	mock.recorder = &MockteamMemberInviterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamMemberInviter) EXPECT() *MockteamMemberInviterMockRecorder {
	return m.recorder
}

// AddMemberWithOutboxEvent mocks base method.
func (m *MockteamMemberInviter) AddMemberWithOutboxEvent(ctx context.Context, teamID, userID int64, role models.Role, event *models.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMemberWithOutboxEvent", ctx, teamID, userID, role, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMemberWithOutboxEvent indicates an expected call of AddMemberWithOutboxEvent.
func (mr *MockteamMemberInviterMockRecorder) AddMemberWithOutboxEvent(ctx, teamID, userID, role, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMemberWithOutboxEvent", reflect.TypeOf((*MockteamMemberInviter)(nil).AddMemberWithOutboxEvent), ctx, teamID, userID, role, event)
}

// MockinviteUserFinder is a mock of inviteUserFinder interface.
type MockinviteUserFinder struct {
	ctrl     *gomock.Controller
	recorder *MockinviteUserFinderMockRecorder
	isgomock struct{}
}

// MockinviteUserFinderMockRecorder is the mock recorder for MockinviteUserFinder.
type MockinviteUserFinderMockRecorder struct {
	mock *MockinviteUserFinder
}

// NewMockinviteUserFinder creates a new mock instance.
func NewMockinviteUserFinder(ctrl *gomock.Controller) *MockinviteUserFinder {
	mock := &MockinviteUserFinder{ctrl: ctrl}
	mock.recorder = &MockinviteUserFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinviteUserFinder) EXPECT() *MockinviteUserFinderMockRecorder {
	return m.recorder
}

// FindByEmail mocks base method.
func (m *MockinviteUserFinder) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockinviteUserFinderMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockinviteUserFinder)(nil).FindByEmail), ctx, email)
}
