// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=report_top_creators
//

// Package report_top_creators is a generated GoMock package.
package report_top_creators

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MocktopCreatorsProvider is a mock of topCreatorsProvider interface.
type MocktopCreatorsProvider struct {
	ctrl     *gomock.Controller
	recorder *MocktopCreatorsProviderMockRecorder
	isgomock struct{}
}

// MocktopCreatorsProviderMockRecorder is the mock recorder for MocktopCreatorsProvider.
type MocktopCreatorsProviderMockRecorder struct {
	mock *MocktopCreatorsProvider
}

// NewMocktopCreatorsProvider creates a new mock instance.
func NewMocktopCreatorsProvider(ctrl *gomock.Controller) *MocktopCreatorsProvider {
	mock := &MocktopCreatorsProvider{ctrl: ctrl}
	mock.recorder = &MocktopCreatorsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktopCreatorsProvider) EXPECT() *MocktopCreatorsProviderMockRecorder {
	return m.recorder
}

// GetTopCreators mocks base method.
func (m *MocktopCreatorsProvider) GetTopCreators(ctx context.Context, managerID int64) ([]models.TopCreator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopCreators", ctx, managerID)
	ret0, _ := ret[0].([]models.TopCreator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopCreators indicates an expected call of GetTopCreators.
func (mr *MocktopCreatorsProviderMockRecorder) GetTopCreators(ctx, managerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopCreators", reflect.TypeOf((*MocktopCreatorsProvider)(nil).GetTopCreators), ctx, managerID)
}
