// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client_test.go -package=auth_register
//

// Package auth_register is a generated GoMock package.
package auth_register

import (
	context "context"
	reflect "reflect"
	models "task-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockuserCreator is a mock of userCreator interface.
type MockuserCreator struct {
	ctrl     *gomock.Controller
	recorder *MockuserCreatorMockRecorder
	isgomock struct{}
}

// MockuserCreatorMockRecorder is the mock recorder for MockuserCreator.
type MockuserCreatorMockRecorder struct {
	mock *MockuserCreator
}

// NewMockuserCreator creates a new mock instance.
func NewMockuserCreator(ctrl *gomock.Controller) *MockuserCreator {
	mock := &MockuserCreator{ctrl: ctrl}
	mock.recorder = &MockuserCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserCreator) EXPECT() *MockuserCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockuserCreator) Create(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockuserCreatorMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuserCreator)(nil).Create), ctx, user)
}

// MockpasswordHasher is a mock of passwordHasher interface.
type MockpasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordHasherMockRecorder
	isgomock struct{}
}

// MockpasswordHasherMockRecorder is the mock recorder for MockpasswordHasher.
type MockpasswordHasherMockRecorder struct {
	mock *MockpasswordHasher
}

// NewMockpasswordHasher creates a new mock instance.
func NewMockpasswordHasher(ctrl *gomock.Controller) *MockpasswordHasher {
	mock := &MockpasswordHasher{ctrl: ctrl}
	mock.recorder = &MockpasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordHasher) EXPECT() *MockpasswordHasherMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockpasswordHasher) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockpasswordHasherMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockpasswordHasher)(nil).Hash), password)
}

// MocktokenIssuer is a mock of tokenIssuer interface.
type MocktokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MocktokenIssuerMockRecorder
	isgomock struct{}
}

// MocktokenIssuerMockRecorder is the mock recorder for MocktokenIssuer.
type MocktokenIssuerMockRecorder struct {
	mock *MocktokenIssuer
}

// NewMocktokenIssuer creates a new mock instance.
func NewMocktokenIssuer(ctrl *gomock.Controller) *MocktokenIssuer {
	mock := &MocktokenIssuer{ctrl: ctrl}
	mock.recorder = &MocktokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenIssuer) EXPECT() *MocktokenIssuerMockRecorder {
	return m.recorder
}

// NewToken mocks base method.
func (m *MocktokenIssuer) NewToken(user *models.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewToken", user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewToken indicates an expected call of NewToken.
func (mr *MocktokenIssuerMockRecorder) NewToken(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewToken", reflect.TypeOf((*MocktokenIssuer)(nil).NewToken), user)
}
